export const GUIDES_LIST_REQUEST = "GUIDES_LIST_REQUEST";
export const GUIDES_LIST_SUCCESS = "GUIDES_LIST_SUCCESS";
export const GUIDES_LIST_FAIL = "GUIDES_LIST_FAIL";

export const GUIDES_CREATE_REQUEST = "GUIDES_CREATE_REQUEST";
export const GUIDES_CREATE_SUCCESS = "GUIDES_CREATE_SUCCESS";
export const GUIDES_CREATE_FAIL = "GUIDES_CREATE_FAIL";

export const GUIDES_UPDATE_REQUEST = "GUIDES_UPDATE_REQUEST";
export const GUIDES_UPDATE_SUCCESS = "GUIDES_UPDATE_SUCCESS";
export const GUIDES_UPDATE_FAIL = "GUIDES_UPDATE_FAIL";

export const GUIDE_VIEW_REQUEST = "GUIDE_VIEW_REQUEST";
export const GUIDE_VIEW_SUCCESS = "GUIDE_VIEW_SUCCESS";
export const GUIDE_VIEW_FAIL = "GUIDE_VIEW_FAIL";
